steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'venue-voice'
      - '--source=.'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars=OPENAI_API_KEY=${_OPENAI_API_KEY},GOOGLE_AI_API_KEY=${_GOOGLE_AI_API_KEY},ANTHROPIC_API_KEY=${_ANTHROPIC_API_KEY},PERPLEXITY_API_KEY=${_PERPLEXITY_API_KEY},ONTRAPORT_APP_ID=${_ONTRAPORT_APP_ID},ONTRAPORT_API_KEY=${_ONTRAPORT_API_KEY},FIREBASE_API_KEY=${_FIREBASE_API_KEY},FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN},FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID},FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET},FIREBASE_MESSAGING_SENDER_ID=${_FIREBASE_MESSAGING_SENDER_ID},FIREBASE_APP_ID=${_FIREBASE_APP_ID}'
options:
  logging: CLOUD_LOGGING_ONLY
timeout: '1200s'
